<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BrandUp.Extensions.Migrations" Version="10.0.6" />
    <PackageReference Include="BrandUp.MongoDB" Version="10.0.12" />
    <PackageReference Include="BrandUp.Website" Version="10.0.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MegafonATS.Client\MegafonATS.Client.csproj" />
    <ProjectReference Include="..\..\src\MegafonATS.Webhooks\MegafonATS.Webhooks.csproj" />
  </ItemGroup>

</Project>
